<?php 
session_start();
if($_SESSION['user']){	
	session_destroy();
	header("location:index.html");
	//header("location:index.php");
}
else{
	header("location:index.html");
	//header("location:index.php");
}
?>